### ISSUE TITLE
Nodejsで動かない

### ISSUE THREAD

**Issue by fruitriin** [Comamoca/miauth.js#4]
Deno依存パッケージ周りがうまく動かない

viteでバンドルした

**Comment by Comamoca** [comment]
issueありがとうございます。

お手数ですがエラーの原因を把握するために、

- Nodeのバージョン
- 本ライブラリのバージョン
- 使用したコードの全文
- 実行した際に出力されたエラーの全文

(トークンなど機密性の高い情報は省いて大丈夫です)

を返信してくださると幸いです。

**Comment by Comamoca** [comment]
自分の方でも実際に動かしてみましたが、MiAuth.js側で不具合は無さそうでした。
実際に書いてみたプログラムは[こちら](https://github.com/Comamoca/miauth.js/tree/main/exsamples/nodejs)に公開してあるので確認してみてください。

エラーの原因としては、MiAuthの仕様上URLによる確認が終わる前にトークンの取得を行うと正常に認証が行われずエラーになるので、それが原因だと考えられます。
`authUrl()`を使ってURLを取得し、そのURLにアクセスして認証を完了したあとに`getToken()`を実行してみてください。

**Comment by Hide-KC** [comment]
閉じてしまっているIssueで申し訳ありませんが、同様の例外が出たので報告です。
また、全文掲載できずすみません。

VSCode拡張機能開発で`miauth.js`を利用しています。

環境：
* Node v18.16.0
* tsc Version 5.0.4
* miauth 0.0.4

`ky.js`の`ky.post(url)`で例外が発生している模様です。
```
TypeError: globalThis.Headers is not a constructor
    at g (...\node_modules\miauth-js\script\deps\esm.sh\v106\ky@0.33.2\deno\ky.js:40:131)
    at new f (...\node_modules\miauth-js\script\deps\esm.sh\v106\ky@0.33.2\deno\ky.js:90:681)
    at Function.create (...\node_modules\miauth-js\script\deps\esm.sh\v106\ky@0.33.2\deno\ky.js:68:35)
（以下略）
```

発生個所は`getToken()`実行時です。
```ts
（認証ページで許可押下まで待機）
miAuth.getToken().then(result => {
    console.log(result)
    vscode.window.showInformationMessage("アクセストークンの取得に成功しました")
  }).catch(error => {
    console.log(error)
    vscode.window.showErrorMessage("アクセストークンの取得に失敗しました")
  })
```

`getToken`相当の操作を`axios`で実行したところ成功しました。
```ts
（認証ページで許可押下まで待機）
const tokenUri = new URL(
  join("api", "miauth", session, "check"),
  origin,
)

axios.post(
  tokenUri.toString(),
  {},
  {
    headers: {
    'content-type': 'application/json'
  }
  }).then((result) => {
    console.log(result)
    const token = result.data.token
    console.log(token)
    vscode.window.showInformationMessage("アクセストークンの取得に成功しました")
  })
```
