### ISSUE TITLE
getToken時にID等の情報もほしい

### ISSUE THREAD

**Issue by code-raisan** [Comamoca/miauth.js#5]
ユーザー登録の際にID等の情報も必要になるのでトークンだけじゃなくてID等の情報もほしい

**Comment by Comamoca** [comment]
issueありがとうございます。

確認になりますが、IDと言うのはMisskey APIのユーザーのIDということでしょうか？

**Comment by code-raisan** [comment]
MisskeyAPIのユーザーIDと`@user`の方のIDもかな。ついでにユーザー名もほしい気がする
Twitter OAuthだと内部IDとスクリーンIDが認証時に一緒に取得出来て2度APIにアクセスする必要がない仕様になってるから、これもそんな感じだといいなと思って。MiAuthはセッション認証時に一緒にかなり多くのユーザー情報が送られてる来るからせっかくだし全部使えるようにするのもありかなと(まあメインはトークンだと思うから重要度の低そうな情報は一段ネストするのもありかななんて思ったりしてる)

**Comment by Comamoca** [comment]
本ライブラリはあくまでmisskey-jsに実装されていない認証機能を補完するものであり、misskey-jsで実装可能な機能を実装することはこのライブラリの責任範囲から外れてしまうため実装するべきではないと考えています。

それとは別に、misskey-jsの開発体験にはいくらかの問題があるとも考えているので、それについてはまた別のプロジェクトとして実装したいと考えています。

**Comment by code-raisan** [comment]
なーるほど
